server:
  servlet:
    context-path: /challenge/nearest
  port: 9001
spring:
  profiles:
    active: local
  application:
    name: nearest-service

--- #local
spring:
  profiles: local, default
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_DATABASE:pilot}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
      javax:
        persistence:
          create-database-schemas: true
    show-sql: false
logging:
  level:
    org:
      hibernate: INFO